//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seating.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public long TableId { get; set; }
        public int TableNum { get; set; }
        public string Title { get; set; }
        public int NumberOfSeats { get; set; }
        public Nullable<long> PersonId { get; set; }
    }
}
